# Generated by Django 5.0.2 on 2024-03-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_city_name_userprofile_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
