# Generated by Django 5.0.2 on 2024-02-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
